version: 2
updates:
  # Root devDependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-tooling:
        patterns:
          - "*"

  # Core package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    groups:
      dev-tooling:
        dependency-type: "development"
        patterns:
          - "*"

  # CLI package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
    groups:
      production:
        dependency-type: "production"
        patterns:
          - "*"
      dev-tooling:
        dependency-type: "development"
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
